# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-14 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20180114_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ('title',)},
        ),
        migrations.AddField(
            model_name='about',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='about',
            table='About',
        ),
    ]
