# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-17 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20180114_2105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
