# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-14 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(db_index=True, max_length=200)),
                ('county_code', models.CharField(db_index=True, max_length=5)),
            ],
        ),
    ]
