# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-14 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countiesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'verbose_name_plural': 'Counties'},
        ),
    ]
