# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 17:39
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('basicpagesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
