# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicpagesApp', '0002_auto_20180331_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='body',
            field=models.TextField(),
        ),
    ]
