# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-13 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('affiliation_name', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('ref', models.CharField(max_length=200)),
                ('active_website', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Dealer',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('affiliation_name', models.CharField(max_length=200)),
                ('actor', models.CharField(max_length=200)),
                ('ref', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Producer',
                'ordering': ('title',),
            },
        ),
    ]
