# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-13 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directoryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='lat',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='lon',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='actor',
            field=models.CharField(choices=[('coop', 'Cooperative Society'), ('estate_large', 'Estate Producers'), ('estate_small', 'Small estates'), ('factory', 'Factory')], default='estate_small', max_length=20),
        ),
    ]
