# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-14 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directoryApp', '0003_producer_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='county',
            field=models.CharField(blank=True, choices=[('1', '_Unknown'), ('2', 'Baringo'), ('3', 'Bungoma'), ('4', 'Busia'), ('5', 'Embu'), ('6', 'Kakamega'), ('7', 'Kericho'), ('8', 'Kiambu'), ('9', 'Kirinyaga'), ('10', 'Kisii'), ('11', 'Machakos'), ('12', 'Makueni'), ('13', 'Meru'), ('14', 'Migori'), ('15', 'Muranga'), ('16', 'Nakuru'), ('17', 'Nandi'), ('18', 'Nyamira'), ('19', 'Nyeri'), ('20', 'Siaya'), ('21', 'YT'), ('22', 'Makueni'), ('23', 'YT'), ('24', 'Baringo'), ('25', 'Bungoma'), ('26', 'Busia'), ('27', 'Embu'), ('28', 'Kakamega'), ('29', 'Kericho'), ('30', 'Kiambu'), ('31', 'Kirinyaga'), ('32', 'Kisii'), ('33', 'Machakos'), ('34', 'Makueni'), ('35', 'Meru'), ('36', 'Migori'), ('37', 'Muranga'), ('38', 'Nakuru'), ('39', 'Nandi'), ('40', 'Nyamira'), ('41', 'Nyeri'), ('42', 'Siaya'), ('43', 'YT'), ('44', 'Makueni'), ('45', 'YT'), ('46', 'YT'), ('47', 'Makueni')], max_length=200, null=True),
        ),
    ]
