# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-17 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directoryApp', '0008_auto_20180117_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='disambiguation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
