# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-19 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directoryApp', '0009_producer_disambiguation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='affiliation_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='producer',
            name='affiliation_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
