# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-20 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directoryApp', '0010_auto_20180119_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producer',
            name='ref',
        ),
        migrations.AddField(
            model_name='producer',
            name='producer_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
