# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-21 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directoryApp', '0012_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
