# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directoryApp', '0013_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='notes',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
