# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-23 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeGrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffeegrade', models.CharField(db_index=True, max_length=200)),
                ('coffeesize', models.CharField(db_index=True, max_length=5)),
                ('description', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Coffee Grades',
            },
        ),
    ]
