# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-23 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffeegrades',
            old_name='coffeegrade',
            new_name='grade',
        ),
        migrations.RemoveField(
            model_name='coffeegrades',
            name='coffeesize',
        ),
        migrations.AddField(
            model_name='coffeegrades',
            name='size',
            field=models.CharField(choices=[('0 - 5', 'very small'), ('6 - 10', 'small'), ('11 - 15', ',medium'), ('16 - 20', 'large'), ('21 - 25', 'very large')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coffeegrades',
            name='description',
            field=models.TextField(),
        ),
    ]
