# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-23 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directoryApp', '0013_delete_task'),
        ('coffeeApp', '0003_auto_20180123_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TRANSNR', models.CharField(max_length=20)),
                ('LOTNT', models.IntegerField()),
                ('MARKS', models.CharField(max_length=100)),
                ('MARKS2', models.CharField(max_length=100)),
                ('REF2', models.CharField(max_length=20)),
                ('BAGMARK', models.IntegerField()),
                ('BAGSNR', models.CharField(max_length=3)),
                ('WEIGHT_Kgr', models.IntegerField()),
                ('SALENO', models.IntegerField()),
                ('BAGSBOUGHTNR', models.IntegerField()),
                ('WEIGHTBOUGHT_Kgr', models.IntegerField()),
                ('PRICE', models.IntegerField()),
                ('SEATNR', models.IntegerField()),
                ('AUCTCODE', models.IntegerField()),
                ('STATUS', models.IntegerField()),
                ('ISODATE', models.DateTimeField()),
                ('SEASON', models.CharField(max_length=10)),
                ('NOTES', models.TextField()),
                ('BUYERCODE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directoryApp.Dealer')),
                ('GRADE_GR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeApp.CoffeeGrades')),
                ('REF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directoryApp.Producer')),
            ],
            options={
                'verbose_name_plural': 'Nairobi Coffee Exchange Transactions',
            },
        ),
    ]
