# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-23 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeApp', '0004_coffeetransactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeegrades',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coffeegrades',
            name='grade_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='coffeegrades',
            name='size',
            field=models.CharField(blank=True, choices=[('0 - 5', 'very small'), ('6 - 10', 'small'), ('11 - 15', 'medium'), ('16 - 20', 'large'), ('21 - 25', 'very large')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='coffeetransactions',
            name='BAGMARK',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='coffeetransactions',
            name='NOTES',
            field=models.TextField(blank=True, null=True),
        ),
    ]
