# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-23 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeApp', '0005_auto_20180123_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeetransactions',
            name='ISODATE',
            field=models.DateField(),
        ),
    ]
