# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-24 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeApp', '0008_remove_coffeetransactions_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeetransactions',
            name='BUYERCODE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='directoryApp.Dealer'),
        ),
        migrations.AlterField(
            model_name='coffeetransactions',
            name='REF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='directoryApp.Producer'),
        ),
    ]
