# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-25 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directoryApp', '0013_delete_task'),
        ('coffeeApp', '0009_auto_20180124_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffeetransactions',
            old_name='LOTNT',
            new_name='LOTNR',
        ),
        migrations.RemoveField(
            model_name='coffeetransactions',
            name='REF2',
        ),
        migrations.AddField(
            model_name='coffeetransactions',
            name='PRODUCERCODE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='directoryApp.Producer'),
        ),
        migrations.AddField(
            model_name='coffeetransactions',
            name='RESPRICE',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coffeetransactions',
            name='BAGSNR',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coffeetransactions',
            name='GRADE_GR',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coffeeApp.CoffeeGrades'),
        ),
        migrations.AlterField(
            model_name='coffeetransactions',
            name='REF',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
