# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-25 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeApp', '0010_auto_20180125_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeetransactions',
            name='TRANSNR',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
