# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-25 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeApp', '0011_auto_20180125_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeetransactions',
            name='AUCTCODE',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coffeetransactions',
            name='BAGSBOUGHTNR',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coffeetransactions',
            name='BAGSNR',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coffeetransactions',
            name='PRICE',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coffeetransactions',
            name='RESPRICE',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coffeetransactions',
            name='SEATNR',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coffeetransactions',
            name='STATUS',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coffeetransactions',
            name='WEIGHTBOUGHT_Kgr',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coffeetransactions',
            name='WEIGHT_Kgr',
            field=models.IntegerField(null=True),
        ),
    ]
