# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-20 20:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coffeeApp', '0012_auto_20180125_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeetransactions',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='transactions_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
