# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-26 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeApp', '0013_coffeetransactions_users_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffeetransactions',
            old_name='AUCTCODE',
            new_name='auctcode',
        ),
        migrations.RenameField(
            model_name='coffeetransactions',
            old_name='BAGMARK',
            new_name='bagmark',
        ),
        migrations.RenameField(
            model_name='coffeetransactions',
            old_name='BAGSBOUGHTNR',
            new_name='bagsboughtnr',
        ),
        migrations.RenameField(
            model_name='coffeetransactions',
            old_name='BAGSNR',
            new_name='bagsnr',
        ),
        migrations.RenameField(
            model_name='coffeetransactions',
            old_name='BUYERCODE',
            new_name='buyercode',
        ),
        migrations.RenameField(
            model_name='coffeetransactions',
            old_name='GRADE_GR',
            new_name='grade_gr',
        ),
        migrations.RenameField(
            model_name='coffeetransactions',
            old_name='ISODATE',
            new_name='isodate',
        ),
        migrations.RenameField(
            model_name='coffeetransactions',
            old_name='LOTNR',
            new_name='lotnr',
        ),
        migrations.RenameField(
            model_name='coffeetransactions',
            old_name='MARKS',
            new_name='marks',
        ),
        migrations.RenameField(
            model_name='coffeetransactions',
            old_name='MARKS2',
            new_name='marks2',
        ),
        migrations.RenameField(
            model_name='coffeetransactions',
            old_name='NOTES',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='coffeetransactions',
            old_name='PRICE',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='coffeetransactions',
            old_name='PRODUCERCODE',
            new_name='producercode',
        ),
        migrations.RenameField(
            model_name='coffeetransactions',
            old_name='REF',
            new_name='ref',
        ),
        migrations.RenameField(
            model_name='coffeetransactions',
            old_name='RESPRICE',
            new_name='resprice',
        ),
        migrations.RenameField(
            model_name='coffeetransactions',
            old_name='SALENO',
            new_name='saleno',
        ),
        migrations.RenameField(
            model_name='coffeetransactions',
            old_name='SEATNR',
            new_name='seatnr',
        ),
        migrations.RenameField(
            model_name='coffeetransactions',
            old_name='STATUS',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='coffeetransactions',
            old_name='TRANSNR',
            new_name='transnr',
        ),
        migrations.RenameField(
            model_name='coffeetransactions',
            old_name='WEIGHTBOUGHT_Kgr',
            new_name='weightbought_kgr',
        ),
    ]
