# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-02 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeApp', '0014_auto_20180226_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffeetransactions',
            old_name='WEIGHT_Kgr',
            new_name='weight_kgr',
        ),
    ]
